### ISSUE TITLE
Integrate in UITabBarController

### ISSUE THREAD

**Issue by matibzurovski** [DigitalLeaves/DLHamburguerMenu#10]
Is it possible to integrate the menu to a tab bar controller? I would like the menu to appear when the user taps one of the tab bar options.

**Comment by DigitalLeaves** [comment]
Yes, absolutely. You just need to subclass UITabBar and then add a "phantom" UIViewController to it in the storyboard, when you would trigger the menu. Then in the UITabBarController method didSelect... you should just trigger the hamburger menu. Hope it helps!

**Comment by matibzurovski** [comment]
I am not sure what "phantom" UIViewController means. Do you have any example of this? Thanks

**Comment by DigitalLeaves** [comment]
I mean that you should add a UIViewController to the UITabBarController in the storyboard, but this UIViewController won’t do anything, it will just be there for adding another tab to the UITabBarController, and so once you modify the UITabBarController subclass to override the default action when selecting a tab, you can choose to do a different action (have a look at selectedTab property in UITabBarController). Sorry I don’t have code for this I can share publicly.

Best!

**Comment by matibzurovski** [comment]
Ok, but this would make that the part of the screen that is not covered with the sideBar will be white, as it will partially display the new UIViewController. Lets say that the tabBar option that opens the hamburguerMenu is #5, and I currently viewing the viewController from option #2. When I tap #5, I want the user to see that behind the menu the content is the one from #2.

**Comment by DigitalLeaves** [comment]
Not at all. Just override the method so when the user selects #5 no UIViewController is selected/added to the hierarchy. You just have to prevent the UIViewController from being show, instead, call trigger and the hamburger menu will be shown.

**Comment by matibzurovski** [comment]
I am not sure who should be the one implementing DLHamburguerViewController now. Should it be the "phantom" VC?

**Comment by DigitalLeaves** [comment]
No, the “phantom” VC is just an artifact for having the extra tab at the tabbar. Create a new VC with the menu, and launch it (accessing DLHamburguerMenuVC) in your tabbar when selected tab index == phantom VC’s position.

**Comment by yinchenghc** [comment]
@matibzurovski Did you solve this problem?

**Comment by DigitalLeaves** [comment]
Hi Yinchenghc, this is not a problem at all. It's perfectly possible, with just a little knowledge of UITabBarController.
