### ISSUE TITLE
#Convert to latest swift sytax?

### ISSUE THREAD

**Issue by mvalbuquerque** [DigitalLeaves/DLHamburguerMenu#11]
The target “DLHamburguerMenu” contains source code developed with an earlier version of Swift. Choose “Convert” to update the source code in this target to the latest Swift syntax. This action can be performed later using “Convert to Latest Swift Syntax” in the Edit menu.

**Comment by mvalbuquerque** [comment]
After convert project no open. tks

**Comment by DigitalLeaves** [comment]
I don't understand your question. Can you please elaborate?

**Comment by mvalbuquerque** [comment]
Error open the project
