### ISSUE TITLE
Side MenuView appears for swipe from right to left

### ISSUE THREAD

**Issue by sravanco** [DigitalLeaves/DLHamburguerMenu#12]
Steps to reproduce:
1.  Display main content view on screen (e.g., Hide side Menu view )
2. Swipe-Left from right corner of screen.
Result:
Side Menu starts revealing.
Expected:
Side Menu should not reveal. Swiping from right to left should have no effect on side menu revelation.

**Comment by DigitalLeaves** [comment]
Hi @sravanco, thanks for pointing it out to me, I'm in the process of modifying the hamburger menu, add some functionality and adapt it to swift 3, so I will probably upload a new version when I'm done, thanks for the contribution and give me some time to incorporate this to the project.

**Comment by sravanco** [comment]
Hi, thanks for the update. any estimate or guess when you can upload the new version?

**Comment by cloudjanak** [comment]
Can please provide quick solution for this , My app is sticked at here.
Thank you.

**Comment by DigitalLeaves** [comment]
Of course @ZetrixWeb-iOS, I have a lot of work to do, but I will leave everything and work in this for your App.

**Comment by DigitalLeaves** [comment]
Fixed.
