### ISSUE TITLE
On swipe right side menu stretching 

### ISSUE THREAD

**Issue by cloudjanak** [DigitalLeaves/DLHamburguerMenu#14]
![simulator screen shot 02-jun-2016 11 05 17 pm](https://cloud.githubusercontent.com/assets/7457258/15754613/8dec59c8-2916-11e6-8642-5c1e01c6fab9.png)

**Comment by DigitalLeaves** [comment]
Never experienced that. Probably a problem with your layout settings. Definitely not related with the hamburger menu, as you can see in the example code.
