### ISSUE TITLE
Going customviewcontroller without homeviewcontroller when clicking indexpath.row

### ISSUE THREAD

**Issue by Sasikumariosdeveloper** [DigitalLeaves/DLHamburguerMenu#15]
When i click tableview indexpath.row, i want to push customviewcontroller. You wrote code for that one. But there appears MainviewController and then custom view controller displays. How to avoid that.

Thanks in advance

**Comment by DigitalLeaves** [comment]
Sorry, I'm not completely sure I understood your question. Could you explain it with an example?
