### ISSUE TITLE
Is there any way to disabled don't make it full screen when clicked sidebar menu left ?

### ISSUE THREAD

**Issue by kristoff2016** [DigitalLeaves/DLHamburguerMenu#17]

**Comment by DigitalLeaves** [comment]
Hi there, sorry for my late reply. I'm afraid I don't completely understand what you have in mind. Would you mind adding a quick sketch or something to help me figure out what you exactly need to achieve for your app?

**Comment by kristoff2016** [comment]
sidebar on left it will be full screen when Recognize left to right  swipe gesture

**Comment by DigitalLeaves** [comment]
Yes, just adjust the size of the menu view.
