### ISSUE TITLE
Menu is getting stretched to full screen on right swipe.

### ISSUE THREAD

**Issue by kannan-prasad** [DigitalLeaves/DLHamburguerMenu#19]
While swiping the menu to the right direction , it is getting stretched to screen width, Issue is existing in the sample code also.

**Comment by DigitalLeaves** [comment]
I don't know what do you mean by "stretching", can you elaborate and hopefully include an screenshot or video of the issue?

**Comment by kannan-prasad** [comment]
@DigitalLeaves  I have attached the video of the issue

[MenuStretching Issue.zip](https://github.com/DigitalLeaves/DLHamburguerMenu/files/1077102/MenuStretching.Issue.zip)

**Comment by DigitalLeaves** [comment]
Ah, ok, hehehehe. Actually, that's on purpose ;)

**Comment by DigitalLeaves** [comment]
If you don't like that effect, you just have to change the max size in the gesture recognizer as the swipe is being recognized. I'm closing this now.
