### ISSUE TITLE
Pass data via segue when clicking a table cell in the menu

### ISSUE THREAD

**Issue by gnijuohz** [DigitalLeaves/DLHamburguerMenu#2]
Hi, I'm pretty new to iOS programming and I'm wondering how can you pass data to the next scene when clicking a table cell in the menu. In my case I want to set the text of the nav bar of the next scene to be the text of the cell that I just clicked. I figured I probably should do something in the following function but I'm not sure how.

``` swift
    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) { 
        let nvc = self.mainNavigationController()
        if let hamburguerViewController = self.findHamburguerViewController() {
            hamburguerViewController.hideMenuViewControllerWithCompletion({ () -> Void in
                nvc.visibleViewController.performSegueWithIdentifier(self.segues[indexPath.row], sender: nil)
                hamburguerViewController.contentViewController = nvc
            })
        }
    }
```

Here's what I have tried:

``` swift
   func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let nvc = self.mainNavigationController()
        if let hamburguerViewController = self.findHamburguerViewController() {
            hamburguerViewController.hideMenuViewControllerWithCompletion({ () -> Void in
             if let the_controller = nvc.visibleViewController as? TagPostViewController {
                    the_controller.siteURL = NSURL(string: "http://www.example.com")
                nvc.visibleViewController.performSegueWithIdentifier("tags", sender: nil)
                hamburguerViewController.contentViewController = nvc
                }
            })
        }
    }
```

This isn't really a bug/issue but can you update the project with a example where some data is being passed through the segue? I think it will really help newcomers like me.

**Comment by DigitalLeaves** [comment]
Hi @gnijuohz
Normally, that's not the "right" way of passing parameters & data to a UIViewController instantiated by means of a push segue. You should implement prepareForSegue(_:sender:) in the view controller where the segue initiates from. In that method, you should pass the parameters if the target view controller is a TagPostViewController. I.E:
if let the_controller = segue.destinationViewController as? TagPostViewController {
                    the_controller.siteURL = NSURL(string: "http://www.example.com")
}

**Comment by DigitalLeaves** [comment]
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instm/UIViewController/prepareForSegue:sender:

**Comment by gnijuohz** [comment]
Thank you so much for your help! I used `prepareForSegue` and it worked :)
