### ISSUE TITLE
Strange Behaviour while Closing and Opening Menu

### ISSUE THREAD

**Issue by nitinsindhubt** [DigitalLeaves/DLHamburguerMenu#21]
I am facing this problem , after integrating  this menu in my project . some blur view  behind the menu appears .

![simulator screen shot 03-aug-2017 1 33 16 pm](https://user-images.githubusercontent.com/30141402/28912219-fb09c02e-7850-11e7-92f4-be5d09ecfe7e.png)
![simulator screen shot 03-aug-2017 1 33 34 pm](https://user-images.githubusercontent.com/30141402/28912220-fb3d80d0-7850-11e7-9a1f-0fb092fb8662.png)

**Comment by DigitalLeaves** [comment]
Hi there. That problem doesn't seem to be related to the hamburger menu. Probably it's caused by a view that lies at the bottom of your view hierarchy. Good luck finding the issue!
