### ISSUE TITLE
Unrecoginzed Selector

### ISSUE THREAD

**Issue by syedrazackimran** [DigitalLeaves/DLHamburguerMenu#24]
hi,  whenn i try to swipe my menu controller i'm facing this error 
`[.DLHamburguerContainerViewController panGestureRecognized:]: unrecognized selector sent to instance 0x7f9265c0c8a0`

kindly check and do needfully

**Comment by DigitalLeaves** [comment]
Make sure your UINavigationController (DLHamburguerNavigationController) has the method panGestureRecognized. Hope it helps!

**Comment by contreras2004** [comment]
Did you manage to solve this? I have the same issue using Swift 4

**Comment by syedrazackimran** [comment]
@contreras2004 

check with this controller **DLHamburguerNavigationController.swift** 
there have an function name of ` func panGestureRecognized(_ sender: UIPanGestureRecognizer!)`
kindly add **@objc** it'll works fine

**Comment by DigitalLeaves** [comment]
Yes, sorry about that, I will upload a new commit soon. I've been busy with a lot of stuff. Feel free to upload a pull request in case you think it's appropriate. :)
