### ISSUE TITLE
Q: Don't want Demo Main content View Controller

### ISSUE THREAD

**Issue by patelrohan** [DigitalLeaves/DLHamburguerMenu#3]
A really great example.
 I am trying to tweak it to match my need. Current example you provided shows `Demo Main content ViewController` when `DLHamburguerNavigationController` is loaded and `Option1/2/3 View Controllers` are further pushed on Navigation Stack which results in back button like shown below. 
![screen shot 2015-07-20 at 9 05 34 pm](https://cloud.githubusercontent.com/assets/1224661/8791032/37854920-2f23-11e5-82e2-bcb27736a286.png)

What I am trying to do is get rid of `Demo Main content ViewController` and directly load Option 1 View Controller on `DLHamburguerNavigationController` (or setting it as a root view controller.) But real problem occurs when I try to go back to Option 1 from Option 2 via Menu as poptoRootViewController does not work. What I tried: 

```
  func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {

    let nvc = self.mainNavigationController()
    println(indexPath.row)
    if let hamburguerViewController = self.findHamburguerViewController() {

        if (indexPath.row == 0){

            //hamburguerViewController.hideMenuViewControllerWithCompletion(<#completion: ((Void) -> Void)?##(Void) -> Void#>)
            hamburguerViewController.hideMenuViewControllerWithCompletion({ () -> Void in
            nvc.popToRootViewControllerAnimated(true) // <--- Does not take me to Option 1.
            })

        }
        else{
            hamburguerViewController.hideMenuViewControllerWithCompletion({ () -> Void in
            nvc.visibleViewController.performSegueWithIdentifier(self.segues[indexPath.row], sender: nil)
            hamburguerViewController.contentViewController = nvc
            })
        }
    }
}
```

I know this is something not really a correct way but I am thinking what shall I do to achieve this? Any hint towards correct solution would be appreciated. Thanks.

**Comment by DigitalLeaves** [comment]
Thanks @pateirohan, Unfortunately, I think you are breaking the stack structure by doing that. DLHamburguerController is really simple and I think it serves most uses. I'm not quite sure of why you want to get rid of the content view controller, but maybe the DLHamburguerController is not what you are after and you would need to find other solutions.
