### ISSUE TITLE
Gesture Recognizer

### ISSUE THREAD

**Issue by matheuztavarez** [DigitalLeaves/DLHamburguerMenu#4]
Hello, I would like to know how can I completely deactivate the gesture recognizer, because I have one in my view and the one from the menu kinda overlays it and I can't use the one from my view. If there would be any way that I could just activate it in subviews, or deactivate for a sub view in particular it would be awesome too! I already tried putting false on the code to deactivate it but I still can't use mine :(

Thanks in advance! :)

**Comment by DigitalLeaves** [comment]
Hi @matheuztavarez, if you want to eliminate completely the gesture recognizer, you should remove the gestureRecognizer variable from DLHamburguerViewController, and any of its interactions, but I think this is maybe an overkill.

I would suggest you to force the gestureRecognizer of DLHamburguerViewController that your other gesture recognizer fails in order to start acting. This way, it won't interrupt it. One example could be:

```
// code in your UIViewController
var yourGestureRecognizer = ... // initialize it
if let dlHamburguerController = self.findHamburguerViewController {
   dlHamburguerController.gestureRecognizer.requireGestureRecognizerToFail(yourGestureRecognizer)
}
```

Let me know if it helps.
Best

**Comment by matheuztavarez** [comment]
Hi @DigitalLeaves ! Thanks for the quick answer, but it seems that xcode can't find that function requireGestureRecognizerToFail :/

**Comment by DigitalLeaves** [comment]
Sorry @matheuztavarez I wrote the code too quick and messed UIViewController and GestureRecognizer. Please try the above code again (corrected)

```
// code in your UIViewController
var yourGestureRecognizer = ... // initialize it
if let dlHamburguerController = self.findHamburguerViewController {
   dlHamburguerController.gestureRecognizer.requireGestureRecognizerToFail(yourGestureRecognizer)
}
```

https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIGestureRecognizer_Class/index.html#//apple_ref/occ/instm/UIGestureRecognizer/requireGestureRecognizerToFail:

**Comment by matheuztavarez** [comment]
Oh I see, my code ended up like this

```
        if let dlHamburguerGestureRecognizer = self.findHamburguerViewController() {
          dlHamburguerGestureRecognizer.gestureRecognizer!.requireGestureRecognizerToFail(rightSwipe)

        }
```

But It still didn't work, the menu kept appearing, and I tried the reverse way and the same thing happened.. :( And I just tried to deactivate the menu and my swipes work normally... 

And tried also to put everything related to the pan gesture on your files under comments and my swipe wouldn't work neither yours, just like if I put false to disable the gesture, which is weird, kinda it makes an overlay that disables all swipes in a region, at least its what it looks like... 
Hope we can find a solution.. :)

**Comment by DigitalLeaves** [comment]
Hi @matheuztavarez,
You should not use it the other way around (the DLHamburguer gesture recognizer should require your gesture recognizer to fail, so yours will always be considered first). I'm afraid I cannot help you more without knowing your code, I have tried it with other recognizers and it works if you establish a relationship of gesture recognizer dependencies with "requireGestureRecognizerToFail".

Anyway, this is not an issue with the DLHamburguer, but with the code dealing with it, so I'm closing this issue with your permission.
