### ISSUE TITLE
UITableViewCell's swipe gesture is not being recognised

### ISSUE THREAD

**Issue by kublaios** [DigitalLeaves/DLHamburguerMenu#5]
In my VC, HamburguerMenu gets opened for all swipe gestures no matter what the direction is. I suppose this is because it is being triggered by "pan" gestures, not swipe. Is there any particular reason to use pan instead of swipe?

This choice causes my table view's cells not to be editable by swiping to the left since the gesture triggers the menu instead. How can I overcome this?

**Comment by DigitalLeaves** [comment]
Actually, the menu will not open if you pan to the left, up or down, it will only appear if you pan or swipe in the right direction. The calculations are performed in the method "panGestureRecognized" of the class "DLHamburguerContainerViewController". You could tweak it based in the menu position (hamburguerViewController.menuDirection) and add a threshold if you want to make it "harder" for the menu to appear.

As for your table view's issue. You have to make sure that the gesture recognizer of the DLHamburguerMenu requires that your UITableView recognizers fail. This way, it will not collide with them, and the UITableView recognizers will have priority over the menu triggering.

```
// code in your UITableViewController
if let dlHamburguerController = self.findHamburguerViewController {
   if let recognizers = self.tableView.gestureRecognizers {
       for recognizer in recognizers {
           dlHamburguerController.gestureRecognizer.requireGestureRecognizerToFail(recognizer as! UIGestureRecognizer)
       }
   }
}
```

As you suggested, you can also of course substitute the Pan gesture recognizer for a Swipe one.
Hope that helps. Best!
