### ISSUE TITLE
How to change the menu appear to pan edge gesture? 

### ISSUE THREAD

**Issue by jasan-s** [DigitalLeaves/DLHamburguerMenu#6]
I am designing an app that has left and right swipe on the main page. So I want the menu to only appear on the main content page by press of a button or maybe swipe from the edge. Your example has the menu appearing if I swipe left to right anywhere on the screen. Any suggestion for a Newbie!

**Comment by DigitalLeaves** [comment]
Yeah, sure. You can disable the swipe behavior altogether by setting the "gestureEnabled" variable to false in "DLHamburguerViewController". If you want to modify the type of gesture, you could for example change the UIPanGestureRecognizer for a UIEdgeScreenPanGestureRecognizer (https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScreenEdgePanGestureRecognizer_class/index.html#//apple_ref/occ/cl/UIScreenEdgePanGestureRecognizer).

Hope it helps and good luck in your App!

**Comment by sehoi** [comment]
please, try this.

// DLHamburguerNavigationController
class DLHamburguerNavigationController: UINavigationController {

```
override func viewDidLoad() {
    super.viewDidLoad()

    //self.view.addGestureRecognizer(UIPanGestureRecognizer(target: self, action: "panGestureRecognized:"))
    let screenEdgeRecoginzer: UIScreenEdgePanGestureRecognizer! = UIScreenEdgePanGestureRecognizer(target: self, action: "panGestureRecognized:")
    screenEdgeRecoginzer.edges = .Left
    self.view.addGestureRecognizer(screenEdgeRecoginzer)
}
```

...
}
