### ISSUE TITLE
Cocoa pods

### ISSUE THREAD

**Issue by ashishfission** [DigitalLeaves/DLHamburguerMenu#7]
Hi,
Thanks for the wonderful side menu. It works like charm. Could you please add it to cocoa Pods , would be easy to maintain.
Thanks

**Comment by DigitalLeaves** [comment]
Hi @ashishfission,

Indeed, it's something I definitely want to do soon. Thanks for your feedback and suggestion, I will do it as soon as I have some free time.

Will keep you informed in this thread.

**Comment by dimohamdy** [comment]
Fixed Here
pod  'DLHamburguerMenu'

https://github.com/dimohamdy/DLHamburguerMenu

**Comment by DigitalLeaves** [comment]
A proper official port of DLHamburguerMenu, called "DLHamburgerMenu" by contact [at ] digitalleaves[ dot] com, with support for swift 3, has been published. It should appear soon, I guess.
