### ISSUE TITLE
Support swift 2?

### ISSUE THREAD

**Issue by mychaelgo** [DigitalLeaves/DLHamburguerMenu#8]
Support swift 2?

**Comment by moudallal** [comment]
Unfortunately, it does not support Swift 2 :( Still waiting though... I tried modifying to support Swift 2 but then, I got problems with instantiating the ViewControllers.

**Comment by DigitalLeaves** [comment]
Hi, Unfortunately, I don't have a lot of time lately due to work, but I will try to adapt this as soon as possible. I don't think that's going to be that hard if you spend like 5-10 minutes on this, though.

**Comment by moudallal** [comment]
Heya! Fixed it and now it works perfectly with Swift 2. Here's what I did:
When you open the Xcode project, it will ask you to convert to latest Swift syntax, which is great. Then it'll give you 5 errors. 3 of these errors can be fixed automatically by Xcode. The other 2 errors are in DLDemoRootViewController.swift file, the lines in the awakeFromNib function. What you gotta do is to remove the '!' after the 'as' in both lines and add a '?' at the end of both lines.
Voila! I hope I helped! :)

**Comment by DigitalLeaves** [comment]
Hi there! Nice to know you got it working. I will fix it as soon as I have some free time (maybe this christmas season) and upload it, hopefully. Best regards!

**Comment by dimohamdy** [comment]
@DigitalLeaves  please accept pull request 
https://github.com/dimohamdy/DLHamburguerMenu

**Comment by DigitalLeaves** [comment]
Should be ported to swift 3 now.
